<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Delta.Render.Smoke</RootNamespace>
    <AssemblyName>DeltaRender.Smoke</AssemblyName>
    <PackageId>DeltaRender.Smoke</PackageId>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RuntimeIdentifiers>osx-arm64;win-x64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../tools/DeltaRender.FullscreenShaders/DeltaRender.FullscreenShaders.csproj" />
    <ProjectReference Include="../../tools/DeltaRender.UiShaders/DeltaRender.UiShaders.csproj" />
    <ProjectReference Include="..\\..\\src\\DeltaRender\\DeltaRender.csproj" />
    <ProjectReference Include="..\\..\\src\\DeltaRender.Platform.SDL3\\DeltaRender.Platform.SDL3.csproj" />
    <ProjectReference Include="..\\..\\src\\DeltaRender.Vulkan\\DeltaRender.Vulkan.csproj" />
    <PackageReference Include="Silk.NET.MoltenVK.Native" GeneratePathProperty="true" />
    <Content Include="$(PkgSilk_NET_MoltenVK_Native)/runtimes/osx/native/libMoltenVK.dylib" Condition=" '$(RuntimeIdentifier)' == 'osx-arm64' Or '$(RuntimeIdentifier)' == 'osx-x64' ">
      <Link>libMoltenVK.dylib</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="$(PkgSilk_NET_MoltenVK_Native)/runtimes/osx/native/MoltenVK_icd.json" Condition=" '$(RuntimeIdentifier)' == 'osx-arm64' Or '$(RuntimeIdentifier)' == 'osx-x64' ">
      <Link>MoltenVK_icd.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Include="fixtures\compute_double.spv" CopyToOutputDirectory="PreserveNewest" />
    <None Include="shaders\fullscreen-rounded-rectangle.vert.spv" CopyToOutputDirectory="PreserveNewest" />
    <None Include="shaders\fullscreen-rounded-rectangle.frag.spv" CopyToOutputDirectory="PreserveNewest" />
    <None Include="shaders\fullscreen-rounded-rectangle.vert.shader.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="shaders\fullscreen-rounded-rectangle.frag.shader.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="shaders\ui-panel.vert.spv" CopyToOutputDirectory="PreserveNewest" />
    <None Include="shaders\ui-panel.frag.spv" CopyToOutputDirectory="PreserveNewest" />
    <None Include="shaders\ui-panel.vert.shader.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="shaders\ui-panel.frag.shader.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
