<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Delta.Render.Platform.SDL3</RootNamespace>
    <AssemblyName>Delta.Render.Platform.SDL3</AssemblyName>
    <PackageId>Delta.Render.Platform.SDL3</PackageId>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Delta.Render.Core\\Delta.Render.Core.csproj" />
    <PackageReference Include="SDL3-CS" />
    <PackageReference Include="SDL3-CS.Windows" />
    <PackageReference Include="SDL3-CS.Linux" />
    <PackageReference Include="SDL3-CS.MacOS" />
  </ItemGroup>
</Project>
