<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Delta.Render.Text</RootNamespace>
    <AssemblyName>DeltaRender.Text</AssemblyName>
    <PackageId>DeltaRender.Text</PackageId>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeltaRender\DeltaRender.csproj" />
    <ProjectReference Include="../../../DeltaText/src/DeltaText/DeltaText.csproj" />
  </ItemGroup>
</Project>
