<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DeltaRender.Text</RootNamespace>
    <AssemblyName>DeltaRender.Text</AssemblyName>
    <PackageId>DeltaRender.Text</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeltaRender\DeltaRender.csproj" />
    <ProjectReference Include="../../../DeltaText/DeltaText.csproj" />
  </ItemGroup>
</Project>
