<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Delta.Render.Core</RootNamespace>
    <AssemblyName>Delta.Render.Core</AssemblyName>
    <PackageId>Delta.Render.Core</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../DeltaText/Delta.Text.csproj" />
    <ProjectReference Include="../../../DeltaShader/src/Delta.Shader.Abstractions/Delta.Shader.Abstractions.csproj" />
  </ItemGroup>
</Project>
