<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Delta.Render</RootNamespace>
    <AssemblyName>DeltaRender</AssemblyName>
    <PackageId>DeltaRender</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Contract/*.cs" />
    <ProjectReference Include="../../../DeltaDiagnostics/src/Delta.Diagnostics.Contract/Delta.Diagnostics.Contract.csproj" />
    <ProjectReference Include="../../../DeltaShader/src/DeltaShader.Contract/DeltaShader.Contract.csproj" />
  </ItemGroup>
</Project>
